
version: "3"

networks:
  dionaea_local:
  cowrie_local:
  glastopf_local:

services:
  dionaea:
    build: ./dionaea
    container_name: dionaea
    stdin_open: true
    restart: always
    networks:
     - dionaea_local
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "20:20"
     - "21:21"
     - "42:42"
     - "69:69/udp"
     - "8081:80"
     - "135:135"
     - "443:443"
     - "445:445"
     - "1433:1433"
     - "1723:1723"
     - "1883:1883"
     - "3306:3306"
     - "5060:5060"
     - "5060:5060/udp"
     - "5061:5061"
     - "27017:27017"
    image: "ardikabs/dionaea:1.0"
    volumes:
     - /data/dionaea:/opt/dionaea/var/dionaea
     - /data/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
     - /data/dionaea/log:/opt/dionaea/var/log
  
  cowrie:
    build: ./cowrie
    container_name: cowrie
    restart: always
    networks:
    - cowrie_local
    restart: always
    cap_add:
    - NET_BIND_SERVICE
    ports:
    - "22:2222"
    - "23:2223"
    image: "ardikabs/cowrie:1.0"
    volumes:
    - /data/cowrie/keys:/home/cowrie/cowrie/etc
    - /data/cowrie/downloads:/home/cowrie/cowrie/dl
    - /data/cowrie/log:/home/cowrie/cowrie/log
    - /data/cowrie/log/tty:/home/cowrie/cowrie/log/tty

  glastopf:
    build: ./glastopf
    container_name: glastopf
    restart: always
    networks:
     - glastopf_local
    ports:
     - "80:80"
    image: "ardikabs/glastopf:1.0"
    volumes:
     - /data/glastopf/db:/opt/glastopf/db
     - /data/glastopf/log:/opt/glastopf/log

  fluentbit:
    container_name: fluentbit
    depends_on:
      - dionaea
      - cowrie
      - glastopf
    restart: always
    image: "fluent/fluent-bit:latest"
    volumes:
      - ./fluentbit/conf:/fluent-bit/etc
      - /data/dionaea:/data/dionaea
      - /data/glastopf:/data/glastopf
      - /data/cowrie:/data/cowrie

  # fluentd:
  #   container_name: fluentd
  #   restart: always
  #   image: "fluent/fluentd:v0.12-debian"
  #   volumes:
  #     - ./fluentd/conf:/fluentd/etc